name: caspa_v2
description: Caspa LLC
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.1+23

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  animate_do: ^2.1.0
  flutter_screenutil: ^5.5.3+2
  google_fonts:
  flutter_svg:
  cupertino_icons: ^1.0.5
  focus_detector: ^2.0.1
  animations:
  rxdart:
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  url_launcher: ^6.0.8
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  http: ^0.13.4
  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0
  sliver_tools: ^0.2.5
  device_info_plus: ^4.1.2
  device_information: ^0.0.4
  package_info_plus: ^1.4.3+1
  grouped_list: ^5.1.2
  equatable: ^2.0.3

  #  flutter_scrolling_fab_animated: ^0.1.3+2
  #  flutter_spinning_wheel: ^1.1.0


  #firebase \\ notification:
  firebase_messaging: ^12.0.1
  firebase: ^9.0.3
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_remote_config: ^2.0.13
  cloud_firestore: ^3.4.3


  awesome_notifications: any
  bot_toast: ^4.0.1
  flutter_local_notifications: ^9.3.2


  image_picker: ^0.8.5+3
  nil:
  #geolocator: ^7.7.1
  permission_handler: ^9.2.0

  #  sentry_flutter: ^6.2.2
  logging: ^1.0.2



  #ui
  lottie: ^1.3.0
  marquee: ^2.2.0
  spring: ^2.0.2
  keyboard_attachable: ^2.1.0
  custom_pop_up_menu: ^1.2.4
  flutter_slidable: ^2.0.0
  story_view: ^0.13.2
  modal_bottom_sheet: ^2.1.0

  #webiew
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.4.3+7
  external_app_launcher: ^2.0.2


  #maps
  google_maps_flutter: ^2.1.7
  geocoding: ^2.0.4
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.1
  geocoder2: ^1.1.2

  geocode: ^1.0.1
  location:

  #pdf
  flutter_cached_pdfview: ^0.4.1

  #permissions
  app_settings: ^4.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  logger: ^1.1.0


dependency_overrides:


flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/anim/
    - assets/sounds/
  fonts:
    - family: Co Headline
      fonts:
        - asset: assets/fonts/coheadline.otf
          style: normal
    - family: San Francisco
      fonts:
        - asset: assets/fonts/SFNSText-Regular.otf
          style: normal
          weight: 700
